services:
    _defaults:
        autowire: true
        autoconfigure: true

    Disjfa\MailBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\MailBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        Disjfa\MailBundle\Mail\MailInterface:
            tags: ['disjfa.mail']

    Disjfa\MailBundle\Mail\MailCollection:
        arguments:
            - !tagged disjfa.mail


