services:
    _defaults:
        autowire: true
        autoconfigure: true

    Disjfa\MailBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\MailBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Disjfa\MailBundle\Mail\MailCollection:
        arguments:
            - !tagged disjfa.mail

    Disjfa\MailBundle\Menu\Admin\MailMenuListener:
        autowire: true
        tags:
            - { name: 'kernel.event_listener', event: 'admin.menu_configure', method: 'onMenuConfigure' }
